import React from 'react'
import Thumnail from './Thumnail';

const Right = () => {
  return (
    <div className='flex flex-wrap  w-full h-full dark:bg-black overflow-auto'>
      <Thumnail title={'🔴 Build Youtube Clone using React, Redux, TailwindCSS and Firebase - in Tamil'} channel={'A2D channel'} logo={'https://yt3.googleusercontent.com/42f4O-tN4ZCNZfDuuq4Dto8x-MgbbJj5JqEXYlxaGt6gjO-JtTl4ilpSoSRzXWwouqP_xLk=s160-c-k-c0x00ffffff-no-rj'} thumnail={'https://imgs.search.brave.com/pOaBQnGdotrnHtF_0NMASNCS6LazIYQ19AmbcrWTQmE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/dGVjaHNtaXRoLmNv/bS9ibG9nL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDIxLzAyL1RT/Qy10aHVtYm5haWwt/ZXhhbXBsZS0xMDI0/eDU3Ni5wbmc'} date={'2 days ago'} views={"1M"} />
      <Thumnail title={'Nayanthara x Dhanush Issue! | Madan Gowri | Tamil | MG Squad 🖖'} channel={'MadhanGowri'} logo={'https://yt3.googleusercontent.com/ytc/AIdro_lrMeOj87eBqgzxutjD58IfdwxTzlyfl5JPMd27ga2zeXEi=s160-c-k-c0x00ffffff-no-rj'} thumnail={'https://imgs.search.brave.com/eDlDT01Qt5cUHkAKPVnEHzKfX73r4NfymUcg6iYBhh8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93aWtp/YmlvLmluL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDIyLzAyL01h/ZGFuLUdvd3JpLXdp/dGgtaGlzLW1vdGhl/ci5qcGc'} date={'4 years ago'} views={'3M'} />
      <Thumnail title={'Most expensive cars in the earth'} channel={'MR Beast'} logo={'https://yt3.googleusercontent.com/CDlzAR4NNxsq4YDkEjA-rhrt7faVAm69EvY0UyAqCN0A9NAxK1K9R7msDL6z5P-H5MVs6Nroew=s160-c-k-c0x00ffffff-no-rj'} thumnail={'https://imgs.search.brave.com/Lv5wJ_0_LqLZnoiTgA9w029as1KlUqDxa9-Hj841sGk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9kdWV0/LWNkbi52b3gtY2Ru/LmNvbS90aHVtYm9y/LzB4MDoxMjgweDcy/MC8yNDAweDE2MDAv/ZmlsdGVyczpmb2Nh/bCgyMjd4MzM0OjIy/OHgzMzUpOmZvcm1h/dCh3ZWJwKS9jZG4u/dm94LWNkbi5jb20v/dXBsb2Fkcy9jaG9y/dXNfYXNzZXQvZmls/ZS8yNDkwMDc1NS92/QnBRMVNsZlZ0VV9I/RC5qcGc'} date={'3 years ago'} views={'150M'} />
      <Thumnail title={'How To Create A Tamil Thumbnails In Android Phone | Without Photoshop for YouTube Video'} channel={'A2D channel'} logo={'https://i.ytimg.com/vi/ES330DMMhJk/maxresdefault.jpg'} date={'2 days ago'} views={"1M"} thumnail={'https://i.ytimg.com/vi/-2sW1o5ayvE/maxresdefault.jpg'} />
      <Thumnail title={'Nayanthara x Dhanush Issue! | Madan Gowri | Tamil | MG Squad 🖖'} channel={'MadhanGowri'} logo={'https://yt3.googleusercontent.com/ytc/AIdro_lrMeOj87eBqgzxutjD58IfdwxTzlyfl5JPMd27ga2zeXEi=s160-c-k-c0x00ffffff-no-rj'} thumnail={'https://i.ytimg.com/vi/co7uxONXoVA/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCKDkKAGUaJ0NZ7oBjX1SM68ZvFIw'} date={'4 years ago'} views={'3M'} />
      <Thumnail title={'Most expensive cars in the earth by the mr beast'} channel={'MR Beast'} logo={'https://yt3.googleusercontent.com/CDlzAR4NNxsq4YDkEjA-rhrt7faVAm69EvY0UyAqCN0A9NAxK1K9R7msDL6z5P-H5MVs6Nroew=s160-c-k-c0x00ffffff-no-rj'} thumnail={'https://i.ytimg.com/vi/D4dQ0SjLcSw/maxresdefault.jpg'} date={'3 years ago'} views={'150M'} />
      <Thumnail title={'🔴 Build Youtube Clone using React, Redux, TailwindCSS and Firebase - in Tamil'} channel={'A2D channel'} logo={'https://yt3.googleusercontent.com/42f4O-tN4ZCNZfDuuq4Dto8x-MgbbJj5JqEXYlxaGt6gjO-JtTl4ilpSoSRzXWwouqP_xLk=s160-c-k-c0x00ffffff-no-rj'} thumnail={'https://i.ytimg.com/vi/htMaQIPZlmQ/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLC_ONhE1kG55L91S_vcZPyny2qiqA'} date={'2 days ago'} views={"1M"} />
      <Thumnail title={'Nayanthara x Dhanush Issue! | Madan Gowri | Tamil | MG Squad 🖖'} channel={'MadhanGowri'} logo={'https://yt3.googleusercontent.com/ytc/AIdro_lrMeOj87eBqgzxutjD58IfdwxTzlyfl5JPMd27ga2zeXEi=s160-c-k-c0x00ffffff-no-rj'} thumnail={'https://imgs.search.brave.com/eDlDT01Qt5cUHkAKPVnEHzKfX73r4NfymUcg6iYBhh8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93aWtp/YmlvLmluL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDIyLzAyL01h/ZGFuLUdvd3JpLXdp/dGgtaGlzLW1vdGhl/ci5qcGc'} date={'4 years ago'} views={'3M'} />
      <Thumnail title={'Most expensive cars in the earth'} channel={'MR Beast'} logo={'https://yt3.googleusercontent.com/CDlzAR4NNxsq4YDkEjA-rhrt7faVAm69EvY0UyAqCN0A9NAxK1K9R7msDL6z5P-H5MVs6Nroew=s160-c-k-c0x00ffffff-no-rj'} thumnail={'https://i.ytimg.com/vi/fJUI_h_ApAc/maxresdefault.jpg'} date={'3 years ago'} views={'150M'} />
      <Thumnail title={'Most expensive cars in the earth'} channel={'MR Beast'} logo={'https://yt3.googleusercontent.com/CDlzAR4NNxsq4YDkEjA-rhrt7faVAm69EvY0UyAqCN0A9NAxK1K9R7msDL6z5P-H5MVs6Nroew=s160-c-k-c0x00ffffff-no-rj'} thumnail={'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXUY7jhoQ13oDCvUSpN1uf55rtb8FjsCjQXwBvxHxpV2jOez8Ejw-Flmvs2e0gxIdgxpc&usqp=CAU'} date={'3 years ago'} views={'150M'} />
      <Thumnail title={'Most expensive cars in the earth'} channel={'MR Beast'} logo={'https://yt3.googleusercontent.com/CDlzAR4NNxsq4YDkEjA-rhrt7faVAm69EvY0UyAqCN0A9NAxK1K9R7msDL6z5P-H5MVs6Nroew=s160-c-k-c0x00ffffff-no-rj'} thumnail={'https://pbs.twimg.com/media/GZX14pPXwAAYzfH?format=jpg&name=large'} date={'3 years ago'} views={'150M'} />
      <Thumnail title={'Most expensive cars in the earth'} channel={'MR Beast'} logo={'https://yt3.googleusercontent.com/CDlzAR4NNxsq4YDkEjA-rhrt7faVAm69EvY0UyAqCN0A9NAxK1K9R7msDL6z5P-H5MVs6Nroew=s160-c-k-c0x00ffffff-no-rj'} thumnail={'https://i.ytimg.com/vi/a9QlQDZnIYA/maxresdefault.jpg'} date={'3 years ago'} views={'150M'} />

      <Thumnail title={'Most expensive cars in the earth'} channel={'MR Beast'} logo={'https://yt3.googleusercontent.com/CDlzAR4NNxsq4YDkEjA-rhrt7faVAm69EvY0UyAqCN0A9NAxK1K9R7msDL6z5P-H5MVs6Nroew=s160-c-k-c0x00ffffff-no-rj'} thumnail={'https://i.ytimg.com/vi/wF1Xqkfa1KE/hqdefault.jpg'} date={'3 years ago'} views={'150M'} />
      <Thumnail title={'Most expensive cars in the earth'} channel={'MR Beast'} logo={'https://yt3.googleusercontent.com/CDlzAR4NNxsq4YDkEjA-rhrt7faVAm69EvY0UyAqCN0A9NAxK1K9R7msDL6z5P-H5MVs6Nroew=s160-c-k-c0x00ffffff-no-rj'} thumnail={'https://i.ytimg.com/vi/8wTyVQpeRGc/maxresdefault.jpg'} date={'3 years ago'} views={'150M'} />
      <Thumnail title={'Most expensive cars in the earth'} channel={'MR Beast'} logo={'https://yt3.googleusercontent.com/CDlzAR4NNxsq4YDkEjA-rhrt7faVAm69EvY0UyAqCN0A9NAxK1K9R7msDL6z5P-H5MVs6Nroew=s160-c-k-c0x00ffffff-no-rj'} thumnail={'https://www.newsbricks.com/root_upld/general-news/2022/07/56896/org_16594202207041009.jpg'} date={'3 years ago'} views={'150M'} />
      <Thumnail title={'Most expensive cars in the earth'} channel={'MR Beast'} logo={'https://yt3.googleusercontent.com/CDlzAR4NNxsq4YDkEjA-rhrt7faVAm69EvY0UyAqCN0A9NAxK1K9R7msDL6z5P-H5MVs6Nroew=s160-c-k-c0x00ffffff-no-rj'} thumnail={'https://i.ytimg.com/vi/a9QlQDZnIYA/maxresdefault.jpg'} date={'3 years ago'} views={'150M'} />

    </div>
  )
}

export default Right